### ISSUE TITLE
Update to Pino v7

### ISSUE THREAD

**Issue by acidoxee** [relaycorp/pino-cloud-js#77]
# Describe the problem

The lib still relies on Pino v6, and new typings are now included with the v7. The exports are a bit different, for instance `import { LoggerOptions } from 'pino';` would become `import { P } from 'pino';` and usage would be namespaced with `P.LoggerOptions`. This breaks the libs' typings and return type becomes `any`, which in turn breaks our app's typechecking.

# Describe the solution you'd like

Update the library to support Pino v7 and drop DefinitelyTyped typings.

# Describe alternatives you've considered

In the meantime, I've overrided the `getPinoOptions` typings with local types of my own, but it's obviously not great 😉

**Comment by gnarea** [comment]
I've just fixed this in #114
